name: Python Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies and setup the environment
        run: make setup

      - name: Lint with pylint
        run: make lint

      - name: Format with black
        run: make format

      - name: Test with pytest
        run: make test